### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by JoseRodriguez-23620213** [SistemasTecTlaxiaco/infografia-JoseRodriguez-23620213#2]
[Rodriguez Cruz Jose Antonio.pdf](https://github.com/SistemasTecTlaxiaco/infografia-JoseRodriguez-23620213/files/12501840/Rodriguez.Cruz.Jose.Antonio.pdf)

**Comment by 00Asaf00** [comment]
> [Rodriguez Cruz Jose Antonio.pdf](https://github.com/SistemasTecTlaxiaco/infografia-JoseRodriguez-23620213/files/12501840/Rodriguez.Cruz.Jose.Antonio.pdf)
> 

Redacción y Ortografía: 100%
Exposición de Ideas centrales: 75%
Organización de la Información: 75%
Uso de imágenes y colores: 75%
Presentación Visual: 75%
Referencias: 75%
Prestación: 75%

Calificación: 0.2 * 78 = 16

**Comment by josealfredo79** [comment]
@00Asaf00 hace falta la calificación no mayor a 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
